config/routes.rb
Blogadding::Application.routes.draw do
  
  resources :paquetes

  get "chats/index"
  get "chats/client"
  post "chats/windows_chat"
  get "chats/admin_chat/:id/:name", to: "chats#admin_chat", as: "chats_admin_chat"
  mount Ckeditor::Engine => '/ckeditor'
  get "home/action_complete", path: "done"
  root :to => "home#index"
  devise_for :users, :skip => [:registrations] 
  resources :users
  resources :admin, only: [:index]
  resources :blog, only: [:index, :show], as: 'blog', controller: 'blogadd'
  get "package/show/:id", to: "home#show_package", as: "show_package"
  get "home/about", path: "about"
  get "home/packages", path: "packages"
  get "home/news", path: "news"
  #get "home/links", path: "links"
  get "home/contact_us", path: "contact_us"
  get "home/news/:id/show",to: "home#show", as: "news_show"
  post "home/send_contact_message", path: "contact_send"
  post "home/send_reservar", path: "send_reservar"
  post "home/send_reservar_paquete", path: "send_reservar_paquete"
  #pdfs
  get "pdfs/registration_sheet/:id", to: "pdfs#registration_sheet", as:"pdf_registration_sheet"
  #get "pdfs/download/:document", to: "pdfs#download", as:"pdf_download"


  scope :admin do
  	resources :posts
  	resources :categories
  end

  match "/posts/add_new_comment" => "posts#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@paquetes = Paquete.order("RANDOM()").limit(4)
		@posts = Post.all.limit(3).order("created_at DESC")
	end

	def about		
	end

	def packages
		@paquetes = Paquete.all		
	end

	def show_package
		@paquete = Paquete.find(params[:id])		
	end

	def news
  	if params[:search]
			@posts = Post.search(params[:search])
			if @posts.class == Array
			  @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(3) 
			else
			  @posts = @posts.page(params[:page]).per(3)
			end
		else 
			 @posts = Post.all.order('id DESC')
			 @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(3) 
    end
    @recents_posts = Post.first(5).reverse
	end


	def contact_us
	end

	def action_complete
	end

	def show
		@post = Post.find(params[:id])
		@recents_posts = Post.first(5).reverse
	end

	def send_contact_message
	  if verify_recaptcha(attribute: "contact", message: "Oh! It's error with reCAPTCHA!")
	  	ContactMailer.contact(params).deliver
	  	redirect_to home_action_complete_path,  flash: { notice: params[:name]+', ¡Tu mensaje ha sido en enviado!' }	  	
	  else
	  	redirect_to home_contact_us_path, flash: { notice: '<div class="alert alert-danger" role="alert"><b>Error en los datos de envio: </b>'+params[:name]+', ¡Tu mensaje no ha sido en enviado! </div>' }
	  end
	end

	def search_affiliate
    unless params[:search].blank?
      @affiliate = Affiliate.search(params[:search]).first
      if @affiliate.blank?
        redirect_to new_affiliate_path, flash: { danger: 'No se encuenta registrado.' }
      elsif params[:rif_letter] == @affiliate.rif_type
        redirect_to affiliate_path(@affiliate.id)
      else
      	redirect_to new_affiliate_path, flash: { danger: 'No se encuenta registrado.' }
      end
    else
    	redirect_to new_affiliate_path, flash: { danger: 'No se encuenta registrado.' }
    end
  end

  def send_reservar
  	if params[:nombre].blank? and params[:apellido].blank? and params[:cedula].blank? and params[:email].blank?
  		flash[:msn] = "Su petición no fué enviada con exito debido aque los datos del formulario fueron ingresados incorrectamente."
  		redirect_to home_action_complete_path,  flash: { notice: params[:nombre]+', ¡Tu reserva no pudo se procesada!' }		
	else
		ReservaMailer.reserva(params).deliver
		flash[:msn] = "Su petición fué enviada con exito, pronto nos pondremos en contacto con usted."
	  	redirect_to home_action_complete_path,  flash: { notice: params[:nombre]+', ¡Tu reserva ha realizado exitosamente!' }
	end
  end

  def send_reservar_paquete
  	if params[:nombre].blank? and params[:apellido].blank? and params[:cedula].blank? and params[:email].blank?
  		flash[:msn] = "Su petición no fué enviada con exito debido aque los datos del formulario fueron ingresados incorrectamente."
  		redirect_to home_action_complete_path,  flash: { notice: params[:nombre]+', ¡Tu reserva no pudo se procesada!' }		
	else
		ReservaMailer.reserva_paquete(params).deliver
		flash[:msn] = "Su petición fué enviada con exito, pronto nos pondremos en contacto con usted."
	  	redirect_to home_action_complete_path,  flash: { notice: params[:nombre]+', ¡Tu reserva ha realizado exitosamente!' }
	end
  end

end

app/views/home/_inicio.html.haml
= content_for(:title, "Judibana Viajes - Inicio")
%section.home
	.content-home
		= render template: "home/carrucel"
		.image-phone.visible-xs
		.container-orange			
		.container-white		
			.container						
				.row.boxes-home
					.col-lg-5.col-md-5
						.box-home#reservas
							.title-reservas
								%center
									%p 
										%i.fa.fa-plane
										= t('home.reservas.vuelos')
							.form-reservas
								%p
									= t('home.reservas.text_1')
								= form_tag home_send_reservar_path, method: "post" do
									.col-lg-5.col-md-5.col-sm-5
										.col-lg-12.col-md-12.col-sm-12
											= radio_button_tag :theme, 'ida', true
											= t('home.reservas.ida')
										.col-lg-12.col-md-12.col-sm-12
											= radio_button_tag :theme, 'ida_vuelta'
											= t('home.reservas.vuelta')										
									.col-lg-7.col-md-7.col-sm-7									
										.col-lg-12.col-md-12.col-sm-12
											= radio_button_tag :agencia, 'jardin'
											= t('home.reservas.jardin')
										.col-lg-12.col-md-12.col-sm-12
											= radio_button_tag :agencia, 'caribe'
											= t('home.reservas.caribe')

									.row
										.col-lg-12
											= text_field_tag :nombre, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.nombre')}", disabled: "disabled", required: "true"
										.col-lg-12
											= text_field_tag :telefono, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.telefono')}", disabled: "disabled", required: "true"
										.col-lg-12
											= text_field_tag :cedula, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.cedula')}", disabled: "disabled", required: "true"
										.col-lg-12
											= text_field_tag :email, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.email')}", disabled: "disabled", required: "true", type: "email"
										.col-lg-12
											= select_tag :vendedor, options_for_select(["#{t('home.reservas.vendedor')}"]), class: "input-reserva", disabled: "disabled"	, required: "true"
										.col-lg-6.col-md-6
											= select_tag :origen, options_for_select(["#{t('home.reservas.origen')}", "Caracas", "Barquisimeto", "Maracaibo", "Porlamar", "Puerto Ordaz", "Cumaná", "Valencia", "Puerto Cabello", "Las Piedras", "Coro", "Mérida", "Maturin", "El Vigia", "Santo Domingo", "Barcelona", "Canaima"]), class: "input-reserva", disabled: "disabled"	, required: "true"							
										.col-lg-6.col-md-6
											= select_tag :destino, options_for_select(["#{t('home.reservas.destino')}", "Caracas", "Barquisimeto", "Maracaibo", "Porlamar", "Puerto Ordaz", "Cumaná", "Valencia", "Puerto Cabello", "Las Piedras", "Coro", "Mérida", "Maturin", "El Vigia", "Santo Domingo", "Barcelona", "Canaima"]), class: "input-reserva", disabled: "disabled"	, required: "true"
									.row
										.col-lg-6.col-md-6
											= text_field_tag :salida, "#{DateTime.now.strftime("%d/%m/%Y")}", class: "input-reserva date", :placeholder=>"#{t('home.reservas.salida')}", disabled: "disabled", required: "true"																
										.col-lg-6.col-md-6
											- cout = DateTime.now+1	
											= text_field_tag :retorno, "#{cout.strftime("%d/%m/%Y")}", class: "input-reserva date", :placeholder=>"#{t('home.reservas.retorno')}", disabled: "disabled"	, required: "true"
									.row
										.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-right: 0px;"}
											= select_tag :adultos, options_for_select([ "#{t('home.reservas.adultos')}", "1", "2", "3", "4", "5" ], "#{t('home.reservas.adultos')}"), class: "select-reserva"			, disabled: "disabled"					
										.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-left: 0px;padding-right: 0px;"}
											= select_tag :mayores, options_for_select([ "#{t('home.reservas.mayores')}", "1", "2", "3", "4", "5"  ], "#{t('home.reservas.mayores')}"), class: "select-reserva", disabled: "disabled"
										.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-left: 0px;padding-right: 0px;"}
											= select_tag :nino, options_for_select([ "#{t('home.reservas.ninos')}", "1", "2", "3", "4", "5" ], "#{t('home.reservas.ninos')}"), class: "select-reserva", disabled: "disabled"											
										.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-left: 0px;"}
											= select_tag :bebes, options_for_select([ "#{t('home.reservas.bebes')}", "1", "2", "3", "4", "5"  ], "Bébes"), class: "select-reserva", disabled: "disabled"
									= submit_tag "#{t('home.reservas.submit')}", class: "btn-judibana", style:"width:100%",id:"id-btn-reserva", disabled: "disabled"
					.col-lg-7.col-md-7		
						- @paquetes.each do |paquete|
							%br.visible-xs
							.col-lg-6.col-md-6.col-sm-6				
								.box-destino
									%a{ href: "/package/show/#{paquete.id}", "data-no-turbolink"=>'true' }
										.image-destino-1{style:"background: url('#{paquete.image}');background-size: cover;"}
									.title-destino
										.row
											.col-lg-12.col-md-12.col-sm-12.col-xs-12
												%center
													%h3.white-font 
														= paquete.name
				%h1{style:"color:#fa7900;"} 
					= t('home.noticias.titulo')
				%hr
				- @posts.each do |post|
					- if post.public == true
						%br.visible-xs
						.col-lg-4.col-md-4.col-sm-6
							.post-min
								= link_to news_show_path(post.id), class: 'news-title', data: { no_turbolink: true } do
									%h3=post.title
								%i.fa.fa-calendar
								%small= post.created_at.strftime("%B %d, %Y")
								%i.fa.fa-user
								%small= post.user.name
								%i.fa.fa-folder-open
								%small= post.category.name
								.post-image-min
									= image_tag "#{post.image}", class: 'news-image'
							
					

app/views/home/_newsall.html.haml
= content_for(:title, "Judibana Viajes - Noticias")
- @posts.each	do |post|
	.post{ style: 'margin-bottom:15px;'}
		= link_to news_show_path(post.id), class: 'news-title', data: { no_turbolink: true } do
			%h4= post.title
		%i.fa.fa-calendar
		%small= post.created_at.strftime("%B %d, %Y")
		%i.fa.fa-user
		%small= post.user.name
		%i.fa.fa-folder-open
		%small= post.category.name
		- if Blog.commentable
			%small.pull-right= "#{post.comments.count} commets"
			%i.fa.fa-comment.pull-right
		.post-image
			= image_tag "#{post.image}", class: 'news-image'
		.post-text{ class: "#{'delete-image' if params[:action] == 'news'}"}
			%p= "#{post.content.split(" ")[0..80].join(" ")}...".html_safe
	%hr
.row
	%center
		= paginate @posts

app/views/home/_show.html.haml
= content_for(:title, "#{@post.title}")
.post{ style: 'margin-bottom:15px;'}
	= link_to news_show_path(@post.id), class: 'news-title', data: { no_turbolink: true } do
		%h4= @post.title
	%i.fa.fa-calendar
	%small= @post.created_at.strftime("%B %d, %Y")
	%i.fa.fa-user
	%small= @post.user.name
	%i.fa.fa-folder-open
	%small= @post.category.name
	- if Blog.commentable
		%small.pull-right.hidden-xs= "#{@post.comments.count} commets"
		%i.fa.fa-comment.pull-right.hidden-xs
	.post-image
		= image_tag "#{@post.image}", class: 'news-image'
	.post-text
		%p= "#{@post.content}".html_safe
%hr

.col-sm-12.col-md-12.col-sm-12.col-xs-12.socials-shared{ style: "margin-bottom: 15px;"}
	.col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-facebook
		#fb-root
			.fb-like{"data-action" => "like", "data-href" => "#{request.url}", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
	.col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-gplus
		.g-plus{"data-action"=>"share", "data-annotation"=>"bubble"}
	.col-xs-2.col-sm-3.col-md-3.col-lg-2.links-socials#social-twitter
		= link_to "Twittear", "https://twitter.com/share", class: "twitter-share-button", "data-lang" => "es", "data-text" => "#parcatur #{@post.title}", "data-url" => "#{request.url}", "data-via" => "parcatur"
%hr.hidden.xs

- if Blog.comments_facebook
	= render "blogadd/comments_facebook"
	

app/views/home/about.html.haml
= content_for(:title, "Judibana Viajes - Nosotros")
#img-nosotros
	.title		
		.min-title
			Judibana Viajes
		%p 
			=t('about.titulo_1')
.container-orange	
#nosotros
	.container		
		= image_tag "about.png", width: "100%"	
		%br
		.row
			.col-lg-6.col-md-6{align:"justify"}
				= raw t('about.texto_1')
				%br
				%br
				= raw t('about.texto_2')
			%br.visible-xs.visible-sm
			.col-lg-6.col-md-6{align:"justify"}
				= raw t('about.texto_3')
				%br
				%br
				= raw t('about.texto_4')
		%br
		= image_tag "logo.png", width: "50%", class: "logo-about"	
		

app/views/home/action_complete.html.haml
= content_for(:title, "Judibana Viajes - Formulario Enviado")
#img-nosotros
	.title		
		.min-title
			Soporte al Cliente
		%p Judibana Viajes.
.container-orange
#nosotros
	.container
		.done-box
			%center
				%h1{style:"color:#db3807"}
					= flash.notice
				%hr
				%p 
					= flash[:msn]
				%br
				%i.fa-fa-envelope{style:"color:#000"}
				

app/views/home/carrucel.html.erb
<div id="carousel-example-generic" class="carousel slide hidden-xs" data-ride="carousel">
      <ol class="carousel-indicators hidden-xs">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
        <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
        <li data-target="#carousel-example-generic" data-slide-to="3" class=""></li>
        <li data-target="#carousel-example-generic" data-slide-to="4" class=""></li>
        <li data-target="#carousel-example-generic" data-slide-to="5" class=""></li>
        <li data-target="#carousel-example-generic" data-slide-to="6" class=""></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <div class="image-1">
            <div class="text-carrucel-1 visible-md visible-lg">
              <div class="titulo"><h1><center><%= t('home.carrucel.texto_h1') %></center></h1></div>
              <div class="texto"><p><%= t('home.carrucel.texto_p1') %><a data-no-turbolink='true' href="/about" class='btn btn-warning btn-image'><%= t('home.carrucel.ver_mas') %></a> </p></div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="image-2">
            <div class="text-carrucel-2 visible-md visible-lg">
              <div class="titulo"><h1><center><%= t('home.carrucel.texto_h2') %></center></h1></div>
              <div class="texto"><p><%= t('home.carrucel.texto_p2') %><a data-no-turbolink='true' href="/packages" class='btn btn-warning btn-image'><%= t('home.carrucel.ver_mas') %></a> </p></div>
            </div>
          </div>
        </div>
        <div class="item" >
          <div class="image-3">
            <div class="text-carrucel-3 visible-md visible-lg">
              <div class="titulo"><h1><center><%= t('home.carrucel.texto_h3') %></center></h1></div>
              <div class="texto"><p><%= t('home.carrucel.texto_p3') %><button data-toggle="modal" data-target="#myModal" class='btn btn-warning btn-image'><%= t('home.carrucel.ver_mas') %></button></p></div>
            </div>
          </div>
        </div>
        <div class="item" >
          <div class="image-4">
            <div class="text-carrucel-4 visible-md visible-lg">
              <div class="titulo"><h1><center><%= t('home.carrucel.texto_h4') %></center></h1></div>
              <div class="texto"><p><%= t('home.carrucel.texto_p4') %><a target="_blank" data-no-turbolink='true' href="http://www.iatatravelcentre.com/VE-Venezuela-customs-currency-airport-tax-regulations-details.htm" class='btn btn-warning btn-image'><%= t('home.carrucel.ver_mas') %></a> </p></div>
            </div>
          </div>
        </div>
        <div class="item" >
          <div class="image-7">
            <div class="text-carrucel-7 visible-md visible-lg">
              <div class="titulo"><h1><center><%= t('home.carrucel.texto_h5') %> </center></h1></div>              
                <div class="texto"><p><%= t('home.carrucel.texto_p5') %> 
                  <%- if current_user %>
                    <a data-no-turbolink='true' class='btn btn-warning btn-image btn-chat' disabled><%= t('home.carrucel.ver_mas') %></a>
                  <%- else %>
                    <a data-no-turbolink='true' class='btn btn-warning btn-image btn-chat'><%= t('home.carrucel.ver_mas') %></a> 
                  <%- end %>
                </p></div>             
            </div>
          </div>
        </div>
        <div class="item" >
          <div class="image-5">
            <div class="text-carrucel-5 visible-md visible-lg">
              <div class="titulo"><h1><center><%= t('home.carrucel.texto_h6') %></center></h1></div>
              <div class="texto"><p><%= t('home.carrucel.texto_p6') %><a data-no-turbolink='true' href="/packages" class='btn btn-warning btn-image'><%= t('home.carrucel.ver_mas') %></a> </p></div>
            </div>
          </div>
        </div>
        <div class="item" >
          <div class="image-6">
            <div class="text-carrucel-6 visible-md visible-lg">
              <div class="titulo"><h1><center><%= t('home.carrucel.texto_h7') %></center></h1></div>
              <div class="texto"><p><%= t('home.carrucel.texto_p7') %><a data-no-turbolink='true' href="/contact_us" class='btn btn-warning btn-image'><%= t('home.carrucel.ver_mas') %></a> </p></div>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.btn-chat').click(function(){
      if($(".button_chat").attr('disabled')=='disabled'){     
        alert("Este servicio no esta activo en este momento, intente más tarde.");  
      }else{
        newwindow=window.open("chats/client","Chat-Support","toolbar=no, location=no, directories=no, status=no, menubar=no, resizable=no, copyhistory=no,width=500,height=600"); 
      }
    });
    $('.carousel').carousel({
      interval: 160000
    })
  });

</script>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="width:800px">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= image_tag "logo.png", width: "200px"%></h4>
      </div>
      <div class="modal-body">
        <%= image_tag "mapa.png"%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.haml
= render 'inicio'
	

	

app/views/home/news.html.haml
#img-news
	.title		
		.min-title
			= t('noticias.titulo_1')
		%p 
			= t('noticias.titulo_2')
.container-orange
= render "layouts/news"

app/views/home/packages.html.haml
= content_for(:title, "Judibana Viajes - Paquetes")
#img-packages
	.title		
		.min-title
			= t('packages.titulo_1')
		%p 
			= t('packages.titulo_2')
.container-orange	
#packages
	.container
		- @paquetes.each do |paquete|
			.col-lg-4.col-md-4.col-sm-6				
				.box-home
					%a{ href: "/package/show/#{paquete.id}", "data-no-turbolink"=>'true'}
						.image-destino-1{style:"background: url('#{paquete.image}');background-size: cover;"}
					.title-destino
						.row
							.col-lg-12.col-md-12.col-sm-12.col-xs-12
								%h3.white-font 
									= paquete.name

app/views/home/show.html.haml
#img-news
	.title
		%p Página de noticias
		.min-title
			Encuentra todas nuestras noticias aquí.
= render "layouts/news"

app/views/home/show_package.html.haml
= content_for(:title, "Judibana Viajes - Paquetes")
#img-packages
	.title		
		.min-title
			= t('packages.titulo_1')
		%p 
			= t('packages.titulo_2')
.container-orange
#packages
	.container
		.row
			.col-lg-4{style:"padding-top:20px;"}
				.box-home
					.image-destino-1{style:"background: url('#{@paquete.image}');background-size: cover;"}
					.title-destino
						.row
							.col-lg-12.col-md-12.col-sm-12.col-xs-12
								%h3.white-font 
									= @paquete.name
				%p{align:"justify"}
					%label
						= t('packages.descripcion')
					= @paquete.description
			.col-lg-8
				.reserva-package-box
					.form-reservas
						%h1{style:"color:#db3807"} 
							=t('packages.titulo_3')
						%hr
						.form-reservas
							%p Elige la agencia en donde reservarás: 
							= form_tag home_send_reservar_paquete_path, method: "post" do							
								.col-lg-6.col-md-6.col-sm-6
									= radio_button_tag :agencia, 'jardin'
									= t('packages.principal') 
									= t('home.reservas.jardin')									
								.col-lg-6.col-md-6.col-sm-6
									= radio_button_tag :agencia, 'caribe'
									= t('packages.sucursal')  
									= t('home.reservas.caribe')

								.row
									.col-lg-12
										= text_field_tag :nombre, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.nombre')}", disabled: "disabled"
									.col-lg-12
										= text_field_tag :telefono, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.telefono')}", disabled: "disabled"
									.col-lg-12
										= text_field_tag :cedula, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.cedula')}", disabled: "disabled"
									.col-lg-12
										= text_field_tag :email, '', class: "input-reserva", :placeholder=>"#{t('home.reservas.email')}", disabled: "disabled"
									.col-lg-12
										= select_tag :vendedor, options_for_select(["#{t('home.reservas.vendedor')}"]), class: "input-reserva", disabled: "disabled"	, required: "true"
									.col-lg-6.col-md-6
										= select_tag :origen, options_for_select(["#{t('home.reservas.origen')}", "Caracas", "Barquisimeto", "Maracaibo", "Porlamar", "Puerto Ordaz", "Cumaná", "Valencia", "Puerto Cabello", "Las Piedras", "Coro", "Mérida", "Maturin", "El Vigia", "Santo Domingo", "Barcelona", "Canaima"]), class: "input-reserva", disabled: "disabled"											
									.col-lg-6.col-md-6										
										= text_field_tag :destino, @paquete.name, class: "input-reserva", :placeholder=>"#{t('home.reservas.destino')}", disabled: "disabled", readonly:"true"
								.row
									.col-lg-6.col-md-6
										= text_field_tag :salida, "#{DateTime.now.strftime("%d/%m/%Y")}", class: "input-reserva date", :placeholder=>'Salida', disabled: "disabled", required: "true"										
									.col-lg-6.col-md-6
										- cout = DateTime.now+1	
										= text_field_tag :retorno, "#{cout.strftime("%d/%m/%Y")}", class: "input-reserva date", :placeholder=>'Retorno', disabled: "disabled"	, required: "true"
								.row
									.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-right: 0px;"}
										= select_tag :adultos, options_for_select([ "#{t('home.reservas.adultos')}", "1", "2", "3", "4", "5" ], "Adultos"), class: "select-reserva"			, disabled: "disabled"					
									.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-left: 0px;padding-right: 0px;"}
										= select_tag :mayores, options_for_select([ "#{t('home.reservas.mayores')}", "1", "2", "3", "4", "5"  ], "Mayores"), class: "select-reserva", disabled: "disabled"
									.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-left: 0px;padding-right: 0px;"}
										= select_tag :nino, options_for_select([ "#{t('home.reservas.ninos')}", "1", "2", "3", "4", "5" ], "Niños"), class: "select-reserva", disabled: "disabled"											
									.col-lg-3.col-md-3.col-sm-3.col-xs-3{style:"padding-left: 0px;"}
										= select_tag :bebes, options_for_select([ "#{t('home.reservas.bebes')}", "1", "2", "3", "4", "5"  ], "Bébes"), class: "select-reserva", disabled: "disabled"
								= submit_tag "#{t('home.reservas.submit')}", class: "btn-judibana", style:"width:100%",id:"id-btn-reserva", disabled: "disabled"