config/routes.rb
Blogadding::Application.routes.draw do
  
  resources :paquetes

  get "chats/index"
  get "chats/client"
  post "chats/windows_chat"
  get "chats/admin_chat/:id/:name", to: "chats#admin_chat", as: "chats_admin_chat"
  mount Ckeditor::Engine => '/ckeditor'
  get "home/action_complete", path: "done"
  root :to => "home#index"
  devise_for :users, :skip => [:registrations] 
  resources :users
  resources :admin, only: [:index]
  resources :blog, only: [:index, :show], as: 'blog', controller: 'blogadd'
  get "package/show/:id", to: "home#show_package", as: "show_package"
  get "home/about", path: "about"
  get "home/packages", path: "packages"
  get "home/news", path: "news"
  #get "home/links", path: "links"
  get "home/contact_us", path: "contact_us"
  get "home/news/:id/show",to: "home#show", as: "news_show"
  post "home/send_contact_message", path: "contact_send"
  post "home/send_reservar", path: "send_reservar"
  post "home/send_reservar_paquete", path: "send_reservar_paquete"
  #pdfs
  get "pdfs/registration_sheet/:id", to: "pdfs#registration_sheet", as:"pdf_registration_sheet"
  #get "pdfs/download/:document", to: "pdfs#download", as:"pdf_download"


  scope :admin do
  	resources :posts
  	resources :categories
  end

  match "/posts/add_new_comment" => "posts#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
 
end

app/views/layouts/_footer.html.haml
.container-hardorange
	%center
		.col-lg-4.col-md-4.hidden-sm.hidden-xs
			= image_tag 'avavit03.png', width: "300px"
		.col-lg-4.col-md-4{style: "font-size:25px;padding-top:30px"}
			= t('home.items.footer')
		.col-lg-4.col-md-4.hidden-sm.hidden-xs
			= image_tag 'avavit04.png', width: "150px"
%footer#footer-1.bs-docs-footer
	.row
		.col-lg-4.col-md-4.col-sm-4.col-xs-4
			Desarrollado por
			= link_to "http://slicegroup.xyz/" do
				= image_tag 'slice.png', width: "60px", style: "display: inline; margin-left: 5px; margin-bottom: 3px;"
		.col-lg-4.col-md-4.col-sm-4.col-xs-4
			%center
				=t('footer.texto')
		.col-lg-4.col-md-4.col-sm-4.col-xs-4
			.pull-right
				Diseñado por
				= link_to "http://studiomuffin.com/" do
					= image_tag 'muffin.png', width: "80px", style: "display: inline; margin-left: 5px; margin-bottom: 3px;"
		

app/views/layouts/_footertwo.html.haml
%footer#footer-2{ class: "#{'fixed' if params[:action] == 'contact_us'}", style: 'background-color: #213338;' }
	%center
		Todos los derechos reservados 2014. Desarrollado por
		%a{ href: 'http://www.tremmelca.com', target: '_blank' }
			%span TREMMEL

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
	- if msg.is_a?(String)
		.container{ style: "margin-bottom:0px;"}
			%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", style: 'margin-top: 10px; margin-bottom:0px;' }
				%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
				= content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# para editar esta barra se usa el id #navbar-home
#judibana-navbar
  .redes-bar
    .container#container-redes
      .row
        .fb
          %center
            %a{href:"https://www.facebook.com/pages/Judibana-Viajes/1500588213509680", target:"_blank", style:"color:#fff"}
              %i.fa.fa-facebook
        .tw
          %center
            %a{href:"https://twitter.com/judibanaviajes", target:"_blank", style:"color:#fff"}
              %i.fa.fa-twitter

        .col-lg-5.col-md-6.hidden-sm.hidden-xs.pull-right
          .col-lg-6.col-md-6.col-sm-6
            .col-lg-1.col-md-1.com-sm-1
              .contact
                %center
                  %i.fa.fa-envelope 
            .col-lg-6.col-md-6.com-sm-6
              .contac-info
                info@judibanaviajes.com
          .col-lg-6.col-md-6.col-sm-6
            .col-lg-1.col-md-1.com-sm-1
              .contact
                %center
                  %i.fa.fa-phone 
            .col-lg-6.col-md-6.com-sm-6
              .contac-info
                +58(0269)2473659/2461254
    
  %nav.navbar.navbar-default#navbar-home
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = image_tag 'logo-2.png', class: 'logo-brand '
        = #link_to 'Judibana Viaje', root_path, class: 'navbar-brand visible-xs visible-sm'
      .collapse.navbar-collapse
        %ul.nav.navbar-nav.pull-right.hidden-xs
          = render 'layouts/navigation_links'
        %ul.nav.navbar-nav.visible-xs
          = render 'layouts/navigation_links'
.es#link_locales
  = link_to "Es", { :locale => "es" }, data: { no_turbolink: true }
.en#link_locales
  = link_to "En", { :locale => "en" }, data: { no_turbolink: true }

app/views/layouts/_navigation_admin.html.haml
-# para editar esta barra se usa el id #navbar-admin
%nav.navbar.navbar-default#navbar-admin
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_admin_links'

app/views/layouts/_navigation_admin_links.html.haml
- if current_user
	%li{ class: "#{'active' if params[:controller] == 'posts'}" }= link_to 'Posts', posts_path
	- if current_user.has_role? :admin
		%li{ class: "#{'active' if params[:controller] == 'categories'}" }= link_to 'Categorías', categories_path
		%li{ class: "#{'active' if params[:controller] == 'paquetes'}" }= link_to 'Paquetes', paquetes_path
		%li{ class: "#{'active' if params[:controller] == 'chats'}" }= link_to 'Soporte al Cliente', chats_index_path
		%li{ class: "#{'active' if params[:controller] == 'users'}" }= link_to 'Usuarios', users_path
	%li= link_to 'Salir', destroy_user_session_path, method: :delete

app/views/layouts/_navigation_links.html.haml
%li{ class: "#{'enable' if params[:action] == 'index'}" }= link_to "#{t('home.items.index')}", root_path, data: { no_turbolink: true }
%li{ class: "#{'enable' if params[:action] == 'about'}" }= link_to "#{t('home.items.about')}", home_about_path, data: { no_turbolink: true }
%li{ class: "#{'enable' if params[:action] == 'packages'}" }= link_to "#{t('home.items.packages')}", home_packages_path, data: { no_turbolink: true }
%li{ class: "#{'enable' if ['news', 'show'].include? params[:action] and params[:controller] != 'affiliates'  }" }= link_to "#{t('home.items.news')}", home_news_path, data: { no_turbolink: true }
%li{ class: "#{'enable' if params[:action] == 'contact_us'}" }= link_to "#{t('home.items.contact')}", home_contact_us_path, data: { no_turbolink: true }

app/views/layouts/_news.html.haml
%section.news
	.container
		%h2
			.visible-xs{style: "margin-top:15px;"}
				= form_tag home_news_path, :method => 'get' do
					.input-group
						= text_field_tag :search, params[:search], class: "form-control"
						%span.input-group-btn
							= submit_tag "Buscar", :name => nil, class: "form-control"
	

		.col-lg-8.col-md-8.col-sm-8.col-xs-12.news-posts
			- if params[:action] == 'news'
				= render 'newsall'
			- elsif params[:action] == 'show'
				= render 'show'

		.col-lg-4.col-md-4.col-sm-4.col-xs-12
			.widget.hidden-xs
				.widget-header{ style: 'background-color: #fa7900;'}
					%h4= t('noticias.buscar')
				.content-widget
					= form_tag home_news_path, :method => 'get' do
						.input-group
							= text_field_tag :search, params[:search], class: "form-control"
							%span.input-group-btn
								= submit_tag t('noticias.buscar'), :name => nil, class: "form-control"

			.widget
				.widget-header{ style: 'background-color: #fa7900;'}
					%h4= t('noticias.ultimas_noticias')
				.widget-content
					%ul
						- @recents_posts.each do |post|
							%li
								= link_to news_show_path(post.id), class: "news-title", data: { no_turbolink: true } do
									%h4{ style: 'font-size: 14px; font-weight: normal;'}= post.title

			.widget
				.widget-header{ style: 'background-color: #fa7900;'}
					%h4 Tweets
				.widget-content
					%center
						%a.twitter-timeline{ href:"https://twitter.com/PARCATUR", "data-widget-id"=>"#{Blog.widget_twitter_id}", "data-chrome"=>"noheader" } Tweets por @PARCATUR 

%script{ src:"//platform.twitter.com/widgets.js" }

- if params[:action] == 'show'
	:javascript
		!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

		//facebook share
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

		//google+ share
		window.___gcfg = {lang: 'es'};

		(function() {
			var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
			po.src = 'https://apis.google.com/js/platform.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		})();

		//chat-comment-facebook
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.0";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));

app/views/layouts/_script_datatable.html.haml
:javascript
	
	$('.datatable').dataTable({
		"oLanguage": {
			"sProcessing": "Procesando...",
			"sLengthMenu": "Mostrar _MENU_ registros",
			"sZeroRecords": "No se encontraron resultados",
			"sEmptyTable": "Ningún dato disponible en esta tabla",
			"sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
			"sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
			"sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
			"sInfoPostFix": "",
			"sSearch": "<i class='icon-search'></i>",
			"sUrl": "",
			"sInfoThousands": ",",
			"sLoadingRecords": "Cargando...",
			"oPaginate": {
				"sFirst": "Primero",
				"sLast": "Último",
				"sNext": "Siguiente",
				"sPrevious": "Anterior"
			},
			"oAria": {
				"sSortAscending": ": Activar para ordenar la columna de manera ascendente",
				"sSortDescending": ": Activar para ordenar la columna de manera descendente"
			}
		},
		"sPaginationType": "bootstrap"
	});

app/views/layouts/application.html.haml
!!!
%html
  %head
    = favicon_link_tag 'favicon.png'
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Agencia de Viajes en Venezuela - Judibana Viajes'
    %script{src:"https://maps.googleapis.com/maps/api/js?sensor=false"}
    %script{ src:"https://cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.1/socket.io.min.js" }
    %script
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-62982236-1', 'auto');
      ga('send', 'pageview');
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'La agencia de viajes judibana con mas de 50 años de experiencia cuenta con un equipo altamente profesional, que está a la vanguardia de los nuevos tiempos para satisfacer las exigencias, viaja y vive tus sueños con nosotros..'}"}
    %link{ href:'http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300', rel:'stylesheet', type:'text/css' }
    %link{ href:"http://fonts.googleapis.com/css?family=Raleway:400,900", rel:"stylesheet", type:"text/css" }
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script
      var socket = io.connect('//judibanaviajes.com:3002/');
      - if current_user
        socket.emit("conectar_admin", { 'name': "#{current_user.name}", 'id': "#{current_user.id}", 'role': "#{current_user.roles.first.name}" });
  %body
    - if ['home'].include? params[:controller] #lista de controladores que se mostraran en el navbar del homepage
      = render 'layouts/navigation'     
    - else #controladores que se mostraran en el navbar de la administracion
      = render 'layouts/navigation_admin'
      = #render 'layouts/messages'
      
    - if ['users', 'categories', 'posts', 'admin', 'chats','paquetes'].include? params[:controller]
      .container.admin
        = yield
    - else
      - unless current_user
        %button.hidden-xs.button_chat.button_enable
          .row
            %b
              = t('home.atencion.titulo')
            .led-online

      = yield
      = render 'layouts/footer'

    - if ['users', 'categories', 'posts', 'admin'].include? params[:controller]
      = #render 'layouts_admin/footeradmin'


:javascript
  $(".button_chat").attr('disabled','disabled');  
  socket.on('button', function(data){
    if (data == true) {
      $(".led-online").css("background", "#2EFE2E")
      $(".led-online").css("box-shadow", "0px 0px 10px #80FF00")
      $(".button_chat").addClass("button_enable")
      $(".button_chat").removeAttr('disabled');
    } else {
      $(".led-online").css("background", "#213338")
      $(".led-online").css("box-shadow", "none")
      $(".button_chat").attr('disabled','disabled');
    }
  });

app/views/layouts/chat.html.haml
%html
	%head
		= favicon_link_tag 'favicon.png'
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
		%title= content_for?(:title) ? yield(:title) : 'Judibana Viajes - Atención al Cliente'
		%link{ href:'http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300', rel:'stylesheet', type:'text/css' }
		%link{ href:"http://fonts.googleapis.com/css?family=Raleway:400,900", rel:"stylesheet", type:"text/css" }
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body#body-chat
		.modal-content
			.modal-header					
				.modal-title 					
					= image_tag 'logo.png', width: '300px'
					%center
						%p							
							- if current_user
								%h4 
									= params[:name].sub("_", " ")
							- else
								%h4 Atención en linea 
			.modal-body
				= yield
			
		